Feat/products
henriqueyun/front-loja-de-roupa pull request #3
Opened 2023-04-27 07:21 UTC by henriqueyun

[[FRONT] Desenvolver tela de produtos](https://trello.com/c/R0LRCJHf)

2023-05-02 21:20 UTC, henriqueyun commented
Ainda falta adicionar o dynamic router

2023-05-05 20:28 UTC, henriqueyun commented
> > O preço não deveria ser uma faixa? tipo de 100 a 200 por exemplo.
> > Acho que o filtro produto não e nescessario, não faz sentido um filtro onde vc coloca todos os produtos para selecionar (Talvez tipo de produto por exemplo em sites de e-commerce na pagina de tenis tem: tenis performance e tenis casual)

- Sobre o component do filtro de preço, sim, deveria ser um [slider](https://mui.com/material-ui/react-slider/) porém vou deixar em backlog pela questão tempo.

- Sobre o filtro de produto, depende. A idéia de produto é que o cara coloque o campo nome com o "tipo" de produto (camiseta, tênis, calça etc.) e adicione o "nome real" do produto na tabela description. Talvez possamos adicionar um novo campo em produto chamado tipo.

2023-05-05 22:30 UTC, coutocouto requested changes
Os valores dos produtos estão sem formatação monetaria

2023-05-05 23:19 UTC, coutocouto approved these changes

2023-05-05 23:19 UTC, merged